version: '3.8'

services:

  postgres:
    image: postgres:17.5-alpine
    environment: 
      - POSTGRES_DB=openfga
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - "29675:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  openfga:
    image: openfga/openfga:v1.8.11
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://admin:123456@postgres:5432/openfga?sslmode=disable
      - OPENFGA_LOG_FORMAT=text
      - OPENFGA_AUTHN_METHOD=preshared
      - OPENFGA_AUTHN_PRESHARED_KEYS=123456
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/openfga migrate && /openfga run"
    ports:
      - "28080:8080" # http
      - "28081:8081" # grpc
      - "23000:3000" # playground
    depends_on:
      postgres:
        condition: service_healthy